// 新規登録用
export const INPUT_EMAIL_FOR_REGISTER = "INPUT_EMAIL_FOR_REGISTER";
export const INPUT_PASSWORD_FOR_REGISTER = "INPUT_PASSWORD_FOR_REGISTER";
export const INPUT_USERNAME_FOR_REGISTER = "INPUT_USERNAME_FOR_REGISTER"
export const RESET_INPUT_FOR_REGISTER = "RESET_INPUT_FOR_REGISTER";

// ログイン用
export const INPUT_EMAIL_FOR_LOGIN = "NPUT_EMAIL_FOR_LOGIN"
export const INPUT_PASSWORD_FOR_LOGIN = "INPUT_PASSWORD_FOR_LOGIN"
export const RESET_INPUT_FOR_LOGIN = "RESET_INPUT_FOR_LOGIN"
