// 新規登録用
export const INPUT_EMAIL_FOR_REGISTER = "INPUT_EMAIL_FOR_REGISTER";
export const INPUT_PASSWARD_FOR_REGISTER = "INPUT_PASSWARD_FOR_REGISTER";
export const INPUT_USERNAME_FOR_REGISTER = "INPUT_USERNAME_FOR_REGISTER"
export const RESET_INPUT_FOR_REGISTER = "RESET_INPUT_FOR_REGISTER";
